name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from tag
      id: extract_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/heads/}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-dockerhub-username/my-image-name:${{ steps.extract_version.outputs.VERSION }}

    - name: Push the Docker image
      run: docker push my-dockerhub-username/my-image-name:${{ steps.extract_version.outputs.VERSION }}

